version: '3.8'
services:
  nodejs:
    build:
      context: .
    image: nitin41/nodejs-mysql-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_PORT=3306
      - MYSQL_USER=sample
      - MYSQL_PASS=sample
      - MYSQL_DB=sampledb
    volumes:
      - ./www/:/var/www/html/
    ports:
      - '3001:8005'
    container_name: moe-nodejs-app
  mysql:
    image: mysql:8.0.21
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sample
      - MYSQL_PASSWORD=sample
      - MYSQL_DATABASE=sampledb
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    container_name: moe-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.4
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - '3002:80'
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
networks:
  frontend:
  backend:
