version: "3.8"
services:
  nodejs:
    build:
      context: .
    image: nitin41/nodejs-mysql-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql-app
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=
      - MYSQL_DB=sampledb
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "3001:8005"
    container_name: nodejs-app
  mysql:
    image: mysql:8.0.21
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=sampledb
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.4
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "3002:80"
    environment:
      - PMA_HOST=mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend:
